# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = LedIndicator(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.widget_3 = LedIndicator(self.frame)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.widget = LedIndicator(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.widget_4 = LedIndicator(self.frame)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout.addWidget(self.widget_4, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 4, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 4, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = LedIndicator(self.frame)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.widget_6 = LedIndicator(self.frame)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3.addWidget(self.widget_6, 5, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 4, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 1, 7, 3, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 4, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 5, 3, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 7, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.pushButton.setText(_translate("MainWindow", "STANDBY"))
        self.pushButton_2.setText(_translate("MainWindow", "REPETITION ON"))
        self.pushButton_3.setText(_translate("MainWindow", "BURST"))
        self.pushButton_4.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.pushButton_5.setText(_translate("MainWindow", "LASER OFF"))
        self.pushButton_6.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.pushButton_7.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label_8.setText(_translate("MainWindow", "closed"))

from LedIndicatorWidget import LedIndicator
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = LedIndicator(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.widget_3 = LedIndicator(self.frame)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.widget = LedIndicator(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.widget_4 = LedIndicator(self.frame)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout.addWidget(self.widget_4, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 4, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 4, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_5 = LedIndicator(self.frame)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.widget_6 = LedIndicator(self.frame)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3.addWidget(self.widget_6, 5, 0, 1, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 4, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        self.spinBox_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 1, 7, 3, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 4, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 5, 3, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 7, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label_8.setText(_translate("MainWindow", "closed"))

from LedIndicatorWidget import LedIndicator
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.laser_on_led = LedIndicator(self.frame)
        self.laser_on_led.setObjectName("laser_on_led")
        self.gridLayout.addWidget(self.laser_on_led, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.repetition_on_led = LedIndicator(self.frame)
        self.repetition_on_led.setObjectName("repetition_on_led")
        self.gridLayout.addWidget(self.repetition_on_led, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.burst_on_led = LedIndicator(self.frame)
        self.burst_on_led.setObjectName("burst_on_led")
        self.gridLayout.addWidget(self.burst_on_led, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.external_trigger_on_led = LedIndicator(self.frame)
        self.external_trigger_on_led.setObjectName("external_trigger_on_led")
        self.gridLayout.addWidget(self.external_trigger_on_led, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 5, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laser_ready_led = LedIndicator(self.frame)
        self.laser_ready_led.setObjectName("laser_ready_led")
        self.horizontalLayout_2.addWidget(self.laser_ready_led)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 6, 1, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repetition_rate_spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox.setFont(font)
        self.repetition_rate_spinBox.setObjectName("repetition_rate_spinBox")
        self.horizontalLayout.addWidget(self.repetition_rate_spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 5, 2)
        self.shutter_status_led = LedIndicator(self.frame)
        self.shutter_status_led.setObjectName("shutter_status_led")
        self.gridLayout_3.addWidget(self.shutter_status_led, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 6, 3, 1, 2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 5, 1)
        self.repetition_rate_spinBox_2 = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repetition_rate_spinBox_2.sizePolicy().hasHeightForWidth())
        self.repetition_rate_spinBox_2.setSizePolicy(sizePolicy)
        self.repetition_rate_spinBox_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox_2.setFont(font)
        self.repetition_rate_spinBox_2.setObjectName("repetition_rate_spinBox_2")
        self.gridLayout_3.addWidget(self.repetition_rate_spinBox_2, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 1)
        self.temperature_bar = QtWidgets.QProgressBar(self.frame)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setOrientation(QtCore.Qt.Vertical)
        self.temperature_bar.setObjectName("temperature_bar")
        self.gridLayout_3.addWidget(self.temperature_bar, 1, 7, 4, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 5, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.label_8.setText(_translate("MainWindow", "closed"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))

from LedIndicatorWidget import LedIndicator
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.laser_on_led = LedIndicator(self.frame)
        self.laser_on_led.setObjectName("laser_on_led")
        self.gridLayout.addWidget(self.laser_on_led, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.repetition_on_led = LedIndicator(self.frame)
        self.repetition_on_led.setObjectName("repetition_on_led")
        self.gridLayout.addWidget(self.repetition_on_led, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.burst_on_led = LedIndicator(self.frame)
        self.burst_on_led.setObjectName("burst_on_led")
        self.gridLayout.addWidget(self.burst_on_led, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.external_trigger_on_led = LedIndicator(self.frame)
        self.external_trigger_on_led.setObjectName("external_trigger_on_led")
        self.gridLayout.addWidget(self.external_trigger_on_led, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 5, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laser_ready_led = LedIndicator(self.frame)
        self.laser_ready_led.setObjectName("laser_ready_led")
        self.horizontalLayout_2.addWidget(self.laser_ready_led)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 6, 1, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repetition_rate_spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox.setFont(font)
        self.repetition_rate_spinBox.setObjectName("repetition_rate_spinBox")
        self.horizontalLayout.addWidget(self.repetition_rate_spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 5, 2)
        self.shutter_status_led = LedIndicator(self.frame)
        self.shutter_status_led.setObjectName("shutter_status_led")
        self.gridLayout_3.addWidget(self.shutter_status_led, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 6, 3, 1, 2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 5, 1)
        self.repetition_rate_spinBox_2 = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repetition_rate_spinBox_2.sizePolicy().hasHeightForWidth())
        self.repetition_rate_spinBox_2.setSizePolicy(sizePolicy)
        self.repetition_rate_spinBox_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox_2.setFont(font)
        self.repetition_rate_spinBox_2.setObjectName("repetition_rate_spinBox_2")
        self.gridLayout_3.addWidget(self.repetition_rate_spinBox_2, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 1)
        self.temperature_bar = QtWidgets.QProgressBar(self.frame)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setOrientation(QtCore.Qt.Vertical)
        self.temperature_bar.setObjectName("temperature_bar")
        self.gridLayout_3.addWidget(self.temperature_bar, 1, 7, 4, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 5, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.label_8.setText(_translate("MainWindow", "closed"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))

from LedIndicatorWidget import LedIndicator
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.laser_on_led = LedIndicator(self.frame)
        self.laser_on_led.setObjectName("laser_on_led")
        self.gridLayout.addWidget(self.laser_on_led, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.repetition_on_led = LedIndicator(self.frame)
        self.repetition_on_led.setObjectName("repetition_on_led")
        self.gridLayout.addWidget(self.repetition_on_led, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.burst_on_led = LedIndicator(self.frame)
        self.burst_on_led.setObjectName("burst_on_led")
        self.gridLayout.addWidget(self.burst_on_led, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.external_trigger_on_led = LedIndicator(self.frame)
        self.external_trigger_on_led.setObjectName("external_trigger_on_led")
        self.gridLayout.addWidget(self.external_trigger_on_led, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 5, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laser_ready_led = LedIndicator(self.frame)
        self.laser_ready_led.setObjectName("laser_ready_led")
        self.horizontalLayout_2.addWidget(self.laser_ready_led)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 6, 1, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repetition_rate_spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox.setFont(font)
        self.repetition_rate_spinBox.setObjectName("repetition_rate_spinBox")
        self.horizontalLayout.addWidget(self.repetition_rate_spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 5, 2)
        self.shutter_status_led = LedIndicator(self.frame)
        self.shutter_status_led.setObjectName("shutter_status_led")
        self.gridLayout_3.addWidget(self.shutter_status_led, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 6, 3, 1, 2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 5, 1)
        self.repetition_quantity_spinBox = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repetition_quantity_spinBox.sizePolicy().hasHeightForWidth())
        self.repetition_quantity_spinBox.setSizePolicy(sizePolicy)
        self.repetition_quantity_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_quantity_spinBox.setFont(font)
        self.repetition_quantity_spinBox.setObjectName("repetition_quantity_spinBox")
        self.gridLayout_3.addWidget(self.repetition_quantity_spinBox, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 1)
        self.temperature_bar = QtWidgets.QProgressBar(self.frame)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setOrientation(QtCore.Qt.Vertical)
        self.temperature_bar.setObjectName("temperature_bar")
        self.gridLayout_3.addWidget(self.temperature_bar, 1, 7, 4, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 5, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.label_8.setText(_translate("MainWindow", "closed"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))

from LedIndicatorWidget import LedIndicator
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 286)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.laser_on_led = LedIndicator(self.frame)
        self.laser_on_led.setObjectName("laser_on_led")
        self.gridLayout.addWidget(self.laser_on_led, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.repetition_on_led = LedIndicator(self.frame)
        self.repetition_on_led.setObjectName("repetition_on_led")
        self.gridLayout.addWidget(self.repetition_on_led, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.burst_on_led = LedIndicator(self.frame)
        self.burst_on_led.setObjectName("burst_on_led")
        self.gridLayout.addWidget(self.burst_on_led, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.external_trigger_on_led = LedIndicator(self.frame)
        self.external_trigger_on_led.setObjectName("external_trigger_on_led")
        self.gridLayout.addWidget(self.external_trigger_on_led, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 5, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laser_ready_led = LedIndicator(self.frame)
        self.laser_ready_led.setObjectName("laser_ready_led")
        self.horizontalLayout_2.addWidget(self.laser_ready_led)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 6, 1, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repetition_rate_spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox.setFont(font)
        self.repetition_rate_spinBox.setObjectName("repetition_rate_spinBox")
        self.horizontalLayout.addWidget(self.repetition_rate_spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 5, 2)
        self.shutter_status_led = LedIndicator(self.frame)
        self.shutter_status_led.setObjectName("shutter_status_led")
        self.gridLayout_3.addWidget(self.shutter_status_led, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 6, 3, 1, 2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 5, 1)
        self.repetition_quantity_spinBox = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repetition_quantity_spinBox.sizePolicy().hasHeightForWidth())
        self.repetition_quantity_spinBox.setSizePolicy(sizePolicy)
        self.repetition_quantity_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_quantity_spinBox.setFont(font)
        self.repetition_quantity_spinBox.setObjectName("repetition_quantity_spinBox")
        self.gridLayout_3.addWidget(self.repetition_quantity_spinBox, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 1)
        self.temperature_bar = QtWidgets.QProgressBar(self.frame)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setOrientation(QtCore.Qt.Vertical)
        self.temperature_bar.setObjectName("temperature_bar")
        self.gridLayout_3.addWidget(self.temperature_bar, 1, 7, 4, 1)
        self.repetition_bar = QtWidgets.QProgressBar(self.frame)
        self.repetition_bar.setProperty("value", 24)
        self.repetition_bar.setObjectName("repetition_bar")
        self.gridLayout_3.addWidget(self.repetition_bar, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 5, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.label_8.setText(_translate("MainWindow", "closed"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))

from LedIndicatorWidget import LedIndicator
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(492, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.laser_on_led = LedIndicator(self.frame)
        self.laser_on_led.setObjectName("laser_on_led")
        self.gridLayout.addWidget(self.laser_on_led, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.repetition_on_led = LedIndicator(self.frame)
        self.repetition_on_led.setObjectName("repetition_on_led")
        self.gridLayout.addWidget(self.repetition_on_led, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.burst_on_led = LedIndicator(self.frame)
        self.burst_on_led.setObjectName("burst_on_led")
        self.gridLayout.addWidget(self.burst_on_led, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.external_trigger_on_led = LedIndicator(self.frame)
        self.external_trigger_on_led.setObjectName("external_trigger_on_led")
        self.gridLayout.addWidget(self.external_trigger_on_led, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 4, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repetition_rate_spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox.setFont(font)
        self.repetition_rate_spinBox.setObjectName("repetition_rate_spinBox")
        self.horizontalLayout.addWidget(self.repetition_rate_spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 2, 4, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laser_ready_led = LedIndicator(self.frame)
        self.laser_ready_led.setObjectName("laser_ready_led")
        self.horizontalLayout_2.addWidget(self.laser_ready_led)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 7, 5, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 8, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 5, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 212, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 9, 4, 1)
        self.temperature_bar = QtWidgets.QProgressBar(self.frame)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setOrientation(QtCore.Qt.Vertical)
        self.temperature_bar.setObjectName("temperature_bar")
        self.gridLayout_3.addWidget(self.temperature_bar, 1, 10, 4, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 212, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 11, 4, 1)
        self.repetition_quantity_spinBox = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repetition_quantity_spinBox.sizePolicy().hasHeightForWidth())
        self.repetition_quantity_spinBox.setSizePolicy(sizePolicy)
        self.repetition_quantity_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_quantity_spinBox.setFont(font)
        self.repetition_quantity_spinBox.setObjectName("repetition_quantity_spinBox")
        self.gridLayout_3.addWidget(self.repetition_quantity_spinBox, 2, 5, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 6, 1, 1)
        self.repetition_bar = QtWidgets.QProgressBar(self.frame)
        self.repetition_bar.setProperty("value", 24)
        self.repetition_bar.setObjectName("repetition_bar")
        self.gridLayout_3.addWidget(self.repetition_bar, 4, 5, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 12)
        self.shutter_status_led = LedIndicator(self.frame)
        self.shutter_status_led.setObjectName("shutter_status_led")
        self.gridLayout_3.addWidget(self.shutter_status_led, 6, 0, 2, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 6, 1, 2, 2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 5, 2, 2)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 8, 2, 2)
        spacerItem5 = QtWidgets.QSpacerItem(187, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 7, 3, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.label_8.setText(_translate("MainWindow", "closed"))

from LedIndicatorWidget import LedIndicator
