# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserControlMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 283)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(99999, 99999))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.redetect_com_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redetect_com_button.sizePolicy().hasHeightForWidth())
        self.redetect_com_button.setSizePolicy(sizePolicy)
        self.redetect_com_button.setObjectName("redetect_com_button")
        self.gridLayout_4.addWidget(self.redetect_com_button, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_4.addWidget(self.comboBox, 0, 1, 1, 1)
        self.connection_label = QtWidgets.QLabel(self.centralwidget)
        self.connection_label.setObjectName("connection_label")
        self.gridLayout_4.addWidget(self.connection_label, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.laser_on_led = LedIndicator(self.frame)
        self.laser_on_led.setObjectName("laser_on_led")
        self.gridLayout.addWidget(self.laser_on_led, 0, 0, 1, 1)
        self.standby_button = QtWidgets.QPushButton(self.frame)
        self.standby_button.setObjectName("standby_button")
        self.gridLayout.addWidget(self.standby_button, 0, 1, 1, 1)
        self.repetition_on_led = LedIndicator(self.frame)
        self.repetition_on_led.setObjectName("repetition_on_led")
        self.gridLayout.addWidget(self.repetition_on_led, 1, 0, 1, 1)
        self.repetition_on_button = QtWidgets.QPushButton(self.frame)
        self.repetition_on_button.setObjectName("repetition_on_button")
        self.gridLayout.addWidget(self.repetition_on_button, 1, 1, 1, 1)
        self.burst_on_led = LedIndicator(self.frame)
        self.burst_on_led.setObjectName("burst_on_led")
        self.gridLayout.addWidget(self.burst_on_led, 2, 0, 1, 1)
        self.burst_on_button = QtWidgets.QPushButton(self.frame)
        self.burst_on_button.setObjectName("burst_on_button")
        self.gridLayout.addWidget(self.burst_on_button, 2, 1, 1, 1)
        self.external_trigger_on_led = LedIndicator(self.frame)
        self.external_trigger_on_led.setObjectName("external_trigger_on_led")
        self.gridLayout.addWidget(self.external_trigger_on_led, 3, 0, 1, 1)
        self.external_trigger_on_button = QtWidgets.QPushButton(self.frame)
        self.external_trigger_on_button.setObjectName("external_trigger_on_button")
        self.gridLayout.addWidget(self.external_trigger_on_button, 3, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.laser_off_button = QtWidgets.QPushButton(self.frame)
        self.laser_off_button.setObjectName("laser_off_button")
        self.gridLayout_2.addWidget(self.laser_off_button, 0, 0, 1, 2)
        self.stop_button = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.repetition_rate_spinBox = QtWidgets.QSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_rate_spinBox.setFont(font)
        self.repetition_rate_spinBox.setMaximum(60)
        self.repetition_rate_spinBox.setObjectName("repetition_rate_spinBox")
        self.horizontalLayout.addWidget(self.repetition_rate_spinBox)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.total_shots_label = QtWidgets.QLabel(self.frame)
        self.total_shots_label.setObjectName("total_shots_label")
        self.verticalLayout.addWidget(self.total_shots_label)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 5, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.laser_ready_led = LedIndicator(self.frame)
        self.laser_ready_led.setObjectName("laser_ready_led")
        self.horizontalLayout_2.addWidget(self.laser_ready_led)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 6, 5, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 7, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 8, 2, 1)
        self.temperature_bar = QtWidgets.QProgressBar(self.frame)
        self.temperature_bar.setProperty("value", 24)
        self.temperature_bar.setOrientation(QtCore.Qt.Vertical)
        self.temperature_bar.setObjectName("temperature_bar")
        self.gridLayout_3.addWidget(self.temperature_bar, 1, 9, 4, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 10, 2, 1)
        self.repetition_quantity_spinBox = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repetition_quantity_spinBox.sizePolicy().hasHeightForWidth())
        self.repetition_quantity_spinBox.setSizePolicy(sizePolicy)
        self.repetition_quantity_spinBox.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repetition_quantity_spinBox.setFont(font)
        self.repetition_quantity_spinBox.setMaximum(65000)
        self.repetition_quantity_spinBox.setObjectName("repetition_quantity_spinBox")
        self.gridLayout_3.addWidget(self.repetition_quantity_spinBox, 2, 4, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 3, 5, 1, 1)
        self.repetition_bar = QtWidgets.QProgressBar(self.frame)
        self.repetition_bar.setProperty("value", 24)
        self.repetition_bar.setObjectName("repetition_bar")
        self.gridLayout_3.addWidget(self.repetition_bar, 4, 4, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 5, 0, 1, 11)
        self.shutter_status_led = LedIndicator(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutter_status_led.sizePolicy().hasHeightForWidth())
        self.shutter_status_led.setSizePolicy(sizePolicy)
        self.shutter_status_led.setObjectName("shutter_status_led")
        self.gridLayout_3.addWidget(self.shutter_status_led, 6, 0, 2, 1)
        self.toggle_shutter_button = QtWidgets.QPushButton(self.frame)
        self.toggle_shutter_button.setObjectName("toggle_shutter_button")
        self.gridLayout_3.addWidget(self.toggle_shutter_button, 7, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(162, 17, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 7, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 7, 4, 1, 2)
        self.shutter_status_label = QtWidgets.QLabel(self.frame)
        self.shutter_status_label.setObjectName("shutter_status_label")
        self.gridLayout_3.addWidget(self.shutter_status_label, 7, 8, 1, 2)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Laser Control"))
        self.redetect_com_button.setText(_translate("MainWindow", "Redetect COM ports"))
        self.connection_label.setText(_translate("MainWindow", "Connected to device"))
        self.standby_button.setText(_translate("MainWindow", "STANDBY"))
        self.repetition_on_button.setText(_translate("MainWindow", "REPETITION ON"))
        self.burst_on_button.setText(_translate("MainWindow", "BURST"))
        self.external_trigger_on_button.setText(_translate("MainWindow", "ExT-TRIGGER"))
        self.laser_off_button.setText(_translate("MainWindow", "LASER OFF"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.label_2.setText(_translate("MainWindow", "REP. RATE"))
        self.label_5.setText(_translate("MainWindow", "Hz"))
        self.total_shots_label.setText(_translate("MainWindow", "Total shots:"))
        self.label_6.setText(_translate("MainWindow", "READY"))
        self.label.setText(_translate("MainWindow", "TEMPERATURE"))
        self.label_3.setText(_translate("MainWindow", "QUANTITY"))
        self.toggle_shutter_button.setText(_translate("MainWindow", "TOGGLE SHUTTER"))
        self.label_7.setText(_translate("MainWindow", "Shutter Status:"))
        self.shutter_status_label.setText(_translate("MainWindow", "closed"))

from LedIndicatorWidget import LedIndicator
